development:
  adapter : postgresql
  database: sample_app_development
  username: tarsa
  password:
  host: localhost
  
test: &test
  adapter : postgresql
  database: sample_app_test
  username: tarsa
  password:
  host: localhost
  
cucumber:
  <<: *test